### ISSUE TITLE
Create navbar.

### ISSUE THREAD

**Issue by atharv-av** [acmjec/acmjec-website-hacktoberfest2023#1]
Refer to the Figma design provided in the Readme file and create the navbar component (preferably using TailwindCSS).

**Comment by chetankhandait** [comment]
Greetings! I'm confident in my ability to assist you with your project. Kindly assign the task to me, and I'll get started right away. If you have any specific instructions, feel free to share them with me. I'm looking forward to working with you and delivering excellent results.

**Comment by Kunalrawal07** [comment]
please assign it to me

**Comment by atharv-av** [comment]
Hello Chetan and Kunal, you both have been assigned the issue.
