### ISSUE TITLE
Enhance source code

### ISSUE THREAD

**Issue by atharv-av** [acmjec/acmjec-website-hacktoberfest2023#10]
Check the pull requests #7 and #9. Merge both of the codes so that the landing page as well as the join us section both get rendered. Currently, only the landing page is visible and the join us section from the previous PR has disappeared.

All you need to do is clone the landing page and the join us section PRs (#7 and #9) separately and then merge both of them in such a way that both the components get rendered and not override one another as shown in the attachment.
![image](https://github.com/acmjec/acmjec-website-hacktoberfest2023/assets/96442140/b60d48e7-566b-41a0-8bb3-bceb749723db)

The 4 cards should be below the "why join us" title.

**Comment by A-R-P-I-T-JAIN** [comment]
cleared the issue and submitted my pull request
