### ISSUE TITLE
Creating Signup page

### ISSUE THREAD

**Issue by Ishaa11** [acmjec/acmjec-website-hacktoberfest2023#14]
im working on the signup page as i have worked on similar projects in react

**Comment by riyanrathore26** [comment]
i want to work on this issue
please assign me 
and also add hacktoberfest lable

**Comment by atharv-av** [comment]
Hello Isha & Riyan, sorry for the delay. You both are now assignees.

**Comment by Aabiskar-dhenga** [comment]
hey atharv - av , Can I get the design of this signup page or i should get inspire from other website and  copy like their .

**Comment by atharv-av** [comment]
Hello aabiskar, you can find the Figma design and the instructions for contributing to this project in the README.md file of the main branch of this repository. For your reference, here's the link to the Figma design:
https://www.figma.com/file/N1xdXBgXbmj9MNWTZSRk5L/Untitled?type=design&node-id=0%3A1&mode=design&t=RLyPDJy8SdnxQDm4-1

**Comment by Ishaa11** [comment]
i have made the ui for signup page  
the functionality will be added when backend is started.
 please Accept my PR :)
and close this issue
![Screenshot (34)](https://github.com/acmjec/acmjec-website-hacktoberfest2023/assets/64044485/39a67197-4c3c-44d2-b851-c940b0313765)

**Comment by AkshatSinghThakur** [comment]
Is this issue still open, or its closed.

**Comment by atharv-av** [comment]
> Is this issue still open, or its closed.

The issue is still open, although the UI is made by @Ishaa11 , you can still add the functionalities using OAuth.
