### ISSUE TITLE
Landing page and Join us card fixing

### ISSUE THREAD

**Issue by atharv-av** [acmjec/acmjec-website-hacktoberfest2023#15]
Fix the text positioning of the word "chapter" in the landing page:
![image](https://github.com/acmjec/acmjec-website-hacktoberfest2023/assets/96442140/097d16b6-f554-49c1-abc1-8fee394ad126)

Fix the positioning of the explore button of the 4th card:
![image](https://github.com/acmjec/acmjec-website-hacktoberfest2023/assets/96442140/27c0b979-f833-46a3-bdb4-ae73c2691217)

**Comment by Rahulbarve132** [comment]
i would love to do this , assign this to me

**Comment by atharv-av** [comment]
Hello Bhavesh and Rahul, this issue has been assigned to you.
