### ISSUE TITLE
Join us card hover effect

### ISSUE THREAD

**Issue by atharv-av** [acmjec/acmjec-website-hacktoberfest2023#16]
Add a beautiful hover effect to the join us cards.

**Comment by Rahulbarve132** [comment]
assign this to me

**Comment by atharv-av** [comment]
Hello Rahul, it has been assigned to you.

**Comment by atharv-av** [comment]
Although a PR has been merged for this issue, but being a contributor's creativity, this issue is still open.

**Comment by AkshatSinghThakur** [comment]
I can work on the card effect to make it look more attractive and professional. 
please assign this issue to me.

**Comment by atharv-av** [comment]
> I can work on the card effect to make it look more attractive and professional. 
> please assign this issue to me.

Assigned it to you.
