### ISSUE TITLE
Remove horizontal scroll bar

### ISSUE THREAD

**Issue by atharv-av** [acmjec/acmjec-website-hacktoberfest2023#19]
A horizontal scroll bar in a website is not an example of a good UX. As you can see in the attached screenshot, there's a scroll bar at the bottom of the page which must be taken care of.

![image](https://github.com/acmjec/acmjec-website-hacktoberfest2023/assets/96442140/99a73f80-8926-48e1-997a-cd444855c267)

**Comment by EnigmaByte7** [comment]
i am a beginner, but i can do it

**Comment by atharv-av** [comment]
You've been assigned.

**Comment by Tanishka-22** [comment]
Having the urge to learn more and more I ensure you to be standing on your expectations. Kindly consider me regarding the assignment of this.

**Comment by atharv-av** [comment]
Hey @Tanishka-22 , you are now an assignee.

**Comment by BhaveshDiwale** [comment]
Hi! Please assign me this issue. I wil be able to clear it.

**Comment by atharv-av** [comment]
> Hi! Please assign me this issue. I wil be able to clear it.

Hey, this issue has been closed.
