### ISSUE TITLE
Create landing page.

### ISSUE THREAD

**Issue by atharv-av** [acmjec/acmjec-website-hacktoberfest2023#2]
Refer to the Figma design provided in the Readme file and create the landing page component (preferably using tailwindCSS).
Ensure responsiveness and write clean code. Create separate components for landing page UI and use them together in the LandingPage.jsx file.

**Comment by atharv-av** [comment]
Each separate component of the landing page can be used to generate a pull request and it will be considered for merging as the landing page is a comparatively larger component.

**Comment by A-R-P-I-T-JAIN** [comment]
I would like to contribute to this landing page

**Comment by atharv-av** [comment]
Hello Arpit, this issue has been assigned to you.

**Comment by BhaveshDiwale** [comment]
Hi! I would like to contribute on the Meet Our Team section. Please assign it to me.

**Comment by A-R-P-I-T-JAIN** [comment]
i have created "Meet our Team" section, but for now it is not responsive.

**Comment by AkshatSinghThakur** [comment]
I can make it responsive for every screen sizes.
@atharv-av sir can I start working on it.

**Comment by atharv-av** [comment]
Hello @BhaveshDiwale @A-R-P-I-T-JAIN @AkshatSinghThakur , you may start working. But please keep in mind that you need to create at least one new file for every PR, else it won't be counted. 

For the mentioned section, I'll be creating another issue and I'll assign it to you all by EOD. In the meantime, you guys may start working on the component.

**Comment by AkshatSinghThakur** [comment]
Ok sir

**Comment by atharv-av** [comment]
Please drop a comment on the added issue guys. @BhaveshDiwale @A-R-P-I-T-JAIN @AkshatSinghThakur
