### ISSUE TITLE
Add loading spinner

### ISSUE THREAD

**Issue by atharv-av** [acmjec/acmjec-website-hacktoberfest2023#21]
Create a spinner that spins until the page is rendered.
HINT - You will need to use conditional rendering the page component.

**Comment by AkshatSinghThakur** [comment]
I can add the spinner in the required position sir. You can assign me the issue.
Waiting for your response.

**Comment by atharv-av** [comment]
Hello @AkshatSinghThakur , you're now an assignee for this issue.

**Comment by AkshatSinghThakur** [comment]
I have added the spinner, sir please check it.
