### ISSUE TITLE
Add authentication

### ISSUE THREAD

**Issue by atharv-av** [acmjec/acmjec-website-hacktoberfest2023#29]
The UI for the signup page is completed but currently it is non-functional. Using OAuth, add authentication to the signup page.

**Comment by AkshatSinghThakur** [comment]
I can add Google Auth at sign up sir.

**Comment by atharv-av** [comment]
> I can add Google Auth at sign up sir. I have used it in my earlier project also.

Similarly, you can do it for GitHub also. Try and check it out. Go ahead.

**Comment by AkshatSinghThakur** [comment]
Sir I have added the Google and GitHub login feature in the website.

**Comment by AkshatSinghThakur** [comment]
I have created a new PR sir.
I think now the problem is solved.

**Comment by atharv-av** [comment]
Your PR has been merged. Thank you for the contribution @AkshatSinghThakur
