### ISSUE TITLE
Fix overflow-y

### ISSUE THREAD

**Issue by atharv-av** [acmjec/acmjec-website-hacktoberfest2023#30]
The "Explore" button of the join us cards is not getting fully rendered as shown due to a minor mistake in CSS.

![image](https://github.com/acmjec/acmjec-website-hacktoberfest2023/assets/96442140/abafbb0b-07c6-4055-b920-56d4c61aab11)

**Comment by AkshatSinghThakur** [comment]
I will fix it sir, you can assign this issue to me.

**Comment by atharv-av** [comment]
> I will fix it sir, please assign this issue to me.

Hello, you've been assigned the issue.
