### ISSUE TITLE
"Meet our team" section

### ISSUE THREAD

**Issue by atharv-av** [acmjec/acmjec-website-hacktoberfest2023#39]
Create the team section which houses the details of the team members of ACM JEC. Ensure that it is fully responsive.

**Comment by AkshatSinghThakur** [comment]
I can make a fully responsive meet our team section sir.
Please assign it to me.

**Comment by atharv-av** [comment]
Sure Akshat!

**Comment by A-R-P-I-T-JAIN** [comment]
will make a fully responsive "meet our team" section, assign it to me

**Comment by A-R-P-I-T-JAIN** [comment]
created fully responsive "meet our team" section and submitted my PR
