### ISSUE TITLE
Create the "why join us" section

### ISSUE THREAD

**Issue by atharv-av** [acmjec/acmjec-website-hacktoberfest2023#4]
Create the 4 cards using a reusable utility component and ensure responsiveness in them.

**Comment by BhaveshDiwale** [comment]
Hi! I would like to complete this task as I clearly understand your requirements. Can you please assign this task to me?
Also please confirm that this section will be a React component.

**Comment by BhaveshDiwale** [comment]
Thanks for assigning me the task.
I have successfully created this section and have raised a pull request. Please merge it to your code. Thanks in advance.

**Comment by atharv-av** [comment]
Thanks for your contribution Bhavesh. Congratulations, your pull request has been merged,
