### ISSUE TITLE
[Refactor] Readme.md

### ISSUE THREAD

**Issue by Ghat0tkach** [acmjec/acmjec-website-hacktoberfest2023#6]
Our project currently lacks a well-defined README.md file in the repository, which makes it challenging for potential contributors to understand the project's requirements, and how to get started.

## Proposed Solution:

Edit the current Readme.md file to include information about Hacktoberfest, project prerequisites, instructions for setting up the local development environment, and guidelines for contributing to the project.

## Instructions for Contributors and Guidelines for Readme

- [ ]  Project Introduction: The README should begin with a brief introduction to the project. and include a link to the [Figma](https://www.figma.com/file/N1xdXBgXbmj9MNWTZSRk5L/Untitled?type=design&node-id=0%3A1&mode=design&t=RLyPDJy8SdnxQDm4-1) design for the project.

- [ ]  Hacktoberfest: Mention that this project is participating in Hacktoberfest and provide a link to the official [Hacktoberfest](www.hacktoberfest.com) website for contributors to learn more and sign up.

- [ ]  Prerequisites: Include a section that lists the prerequisites for contributors. Mention that they should have [Node.js](https://nodejs.org/)  and [npm](https://www.npmjs.com/) installed.

- [ ]  Getting Started: Provide clear and detailed instructions for setting up the local development environment. Include commands for cloning the repository, installing dependencies, and starting the development server.

**Comment by BhaveshDiwale** [comment]
Hi! Please assign this task to me as I clearly understand your requirements.
